from django.core.management.base import BaseCommand
from festivalpickr.models import Festival,Band

class Command(BaseCommand):
    help="A script to populate demonstration DB"

    def create_festivals(self):
        festivals={}
        # festivals['Bonnaroo']=['Paul McCartney','Phish','Arctic Monkeys','Post Malone','Odesza','My Morning Jacket','A$AP Rocky','YEAH YEAH YEAHS','Weezer','Greta Van Fleet','Kacey Musgraves','Foster The People','Brockhampton','Illenium','Billy Idol','Joe Russo\'s Almost Dead','Galantis','RUN-DMC','Mac DeMarco','Griz','ZHU','Leon Bridges','6Lack','BlackBear','Jorja Smith','Billie Eillish','SuperJam','Grand Ole Opry','H.E.R','AWOLNATION','Counting Crows','Bebe Rexha','Rex Orange County','VulfPeck','Flux Pavilion','NGHTMRE','Parquet Courts','Pusha T','Cherub','Collective Soul','Margo Price','Vic Mensa','Drive-By Truckers','Slander','Lovelytheband','Juice Wrld','Colter Wall','Slushii','Mandolin Orange','Dopapod','Sheck Wes','Andrew W.K.','The Hold Steady','Coast Modern','Magic!','Robert DeLong','Kevin Morby','Vanic','King Gizzard & The Lizard Wizard','NEEDTOBREATHE','Atlas Genius','Not Your Dope','JPEGMAFIA','Hobo Johnson & The Lovermakers','Big Thief','Smino','Hippo Campus','Gammer','Just A Gent','12th Planet','Tauk','Zomboy','Mickey Vallen','Parcels','Gunna','Skish','Benjamin Booker','Jaykode','CLAVVS','Com Truise','Foxing','The London Souls','Allan Kingdom','Jai Wolf','Cookie Monsta','Alec Benjamin','L Devine','Pete Yorn','Russ Liquid','Jimi Tents','Orkid','Zoogma','Soccer Mommy','The Jungle Giants','Sullivan King','Wade Bowen','Neon Summer','Kid Astray','Paul McDonald','Flamingosis','WALLA','Royal Teeth','Royal Teeth','Molly Burch','Step Rockets','Shallou','Jack Berry','Porch 40']
        festivals['Coachella']=['Childish Gambino','Janelle Monae','the 1975','DJ Snake','Diplo','Rufu Du Sol','Blackpink','Anderson.Paak','The Free Nationals','Kacey Musgraves','Juice WRLD','Ella Mai','Los Tucanes de Tijuana','FISHER','Jaden Smith','Kraviz','Rosalia','Mon Laferte','Gorgon City','Kruangbin','Kayzo','dvsn','King Princess','Chris Lake','Jauz','Hot Since 82','Charlotte Gainsbourg','SOPHIE','Nicole Moudaber','Tierra Whack','Polo & Pan','Beach Fossils','Yellow Days',' The Frights','Nora En Pure','Yves Tumor','SG Lewis','Kero Kero Bonito','JPEGMAFIA','Calypso Rose','Nic Fanciulli','Kolsch','CamelPhat','Let\'s Eat Grandma','U.S. Girls','Anna Lunoe','Amelie Lens','Hurray for the Riff Raff','Walker & Royce','Turnstile','Rat Boy','88Glam','Ross from Friends','Lauren Lane','Still Woozy','Bakar','Blond:ish','Tomasa del Real','Las Robertas','Dave P.','Tame Impala','Solange','Kid Cudi','Aphex Twin','J Balvin','Weezer','Billie Eilish','Bassnectar','Four Tet','Christine & The Queens','Mac Demarco','Wiz Kalifa','Bazzi','Maggie Rogers','Gryffin','Sheck Wes','Bob Moses','Virgil Ablo','Tale of Us','Mr. Eazi','Sabrina Claudio','Ty Segall & White Fence','Deep Dish','Smino','FKJ','The Interruptors','SiR','Idris Elba','Parcels','JAIN','Soulection','Turnover','SALES','Stephan Bodzin','CloZee','ARIZONA','Murderbeatz','Jambinai','Ame','CHON','Little Simz','Adriatique','Lee Burridge','The Garden','Agoria','Hop Along','shame','Superorganism','Ookay','serpentwithfeet','Steady Holiday','Javiera Mena','The Messthetics','The Red Pears','Heidi Lawden','Ariana Grande','Khalid','Zedd','Gesaffelstein','Bad Bunny','Dillon Francis','CHVRCHES','YG','Cirez D','Playboi Carti','H.E.R.','Blood Orange','Pusha T','Unknown Mortal Orchestra','Kaytranada','Gucci Gang','John Hopkins','SOFFI TUKKER','Burna Boy','Lizzo','Dermot Kennedy','SOBxRBE','Clairo','NGHTMRE','Perfume','boy pablo','Guy Gerber','HYUKOH','Emily King','Dennis Lloyd','Alice Merton','Shallou','070 Shake','Soccer Mommy','Rico Nasty','Cola Boyy','Mansionair','Wallows','Nocturnal Sunshine','Dusky','Yotto','Patrice Baumel','Easy Life','Jon Blomqvist','Iceage','Men I Trust','Charlotte de Witte','Social House','Ocho Ojos','Razorbumps','Tara Brooks']
        festivals['ROMP']=['Ricky Skaggs & Kentucky Thunder','Trampled by Turtles','The Del McCroury Band','Patty Loveless','Steve Earle & The Dukes','The Wood Brothers','Rhonda Vincent & The Rage','Billy Strings','Jeff Austin Band','Joe Mullins & The Radio Ramblers']
        festivals['Reggae Rise Up']=['Steel Pulse','Pepper','Common Kings','Sticky Fingers','Josh Heinrichs','Nattali Rize','Bret Bollinger','Oceanstone','Ziggy Marley','Method Man','Redman','J. Boog','Hirie','The Movement','Through The Roots','Arise Roots','Seranation','Summer Survivors','Tribal Seeds','Trevor Hall','Iya Terra','Shwayze','Jah9','Bumpin Uglies','Tribe of I']
        festivals['High Sierra']=['Greensky Bluegrass','Jim James (Full Band)','St. Paul & The Broken Bones','Galactic','Pigeons Playing Ping Pong','Karl Denson’s Tiny Universe','The Marcus King Band','ALO','The Polish Ambassador','The Nth Power','Jennifer Hartswick Band','Cris Jacobs Band','Cha Wa','Ron Artis II & The Truth']
        festivals['Backwoods']=['REZZ','Umphrey\'s McGee','Lettuce','Aqueous','Bleep Bloop','Bookie T','Eoto','Eprom','The Infamous Stringdusters','Minnesota','The Motet','Mystic Grizzly','Peekaboo','Pidgeons Playing Ping Pong','PLS&TY','Squnto','Truth','Yheti','Arkansauce','Combsy','Couch Jackets','Dapolitiks','Dalton Richmond','Deep Sequence','Drifters Mile','El Dub','Escape Tones','Flintwick','Fluff','Fractal Sky','Glass Cannon','Groovement','Jonteal','Kadela','Last Sayso','Lethal Cortex','Linear Symmetry','Meesh','M.O.B','Montu','Motto','Mountain Sprout','NGHTWTCHR','NUGSTUFR','Of Faces','Recycled Funk','Refrakt','Ryan Viser','Snowmass']
        festivals['Hogs for the Cause']=['Trampled by Turtles','Lukas Nelson and the Promise of the Real','The War & Treaty','Dumpstaphunk','George Porter Jr.','Samantha Fish','American Aquarium','Marco Benevento']
        festivals['Innings']=['Incubus','Sheryl Crow','Cake','Grouplove','Blues Traveler','Roger Clyne & The Peacemakers','Black Pistol Fire','Dorothy','The Baseball Project','Eddie Vedder','Jimmy Eat World','Band of Horses','St.Paul & The Broken Bones','Shakey Graves','Liz Phair','Matt Kearney','G.Love & Special Sauce','The Record Company']
        festivals['Gasparilla']=['Gary Clark Jr.','Jared & The Mill','Laurie Berkner','Lukas Nelson and the Promise of the Real','Mr. Tommy','New Orleans Suspects\' Tribal Gold','Parrotfish','Sugar Rush','Tank and the Bangas','The Avett Brothers','The Infamous Stringdusters','The Pharcyde','Uncle John\'s Band']
        for festival in festivals:
            if not Festival.objects.filter(name__iexact=festival).exists():
                print("adding {}".format(festival))
                festival_entry=Festival(name=festival)
                festival_entry.save()
            festival_row=Festival.objects.get(name__iexact=festival)
            for artist in festivals[festival]:
                if not Band.objects.filter(name__iexact=artist).exists():
                    print("adding both a new band and linking {}".format(festival))
                    band_entry=Band(name=artist)
                    band_entry.save()
                    band_entry.festivals.add(festival_row)
                else:
                    print("linking {}".format(festival))
                    #Band.objects.get(name__iexact=artist).festivals.add(festival_row)
                    bandrows=Band.objects.filter(name__iexact=artist)
                    for row in bandrows:
                        row.festivals.add(festival_row)
    def handle(self, *args, **options):
        self.create_festivals()
