from django.core.management.base import BaseCommand
from festivalpickr.models import Festival,Band

class Command(BaseCommand):
    help="A script to populate demonstration DB"

    def create_festivals(self):
        festivals={}
        # festivals['Coachella']=['Childish Gambino','Janelle Monae','the 1975','DJ Snake','Diplo','Rufu Du Sol','Blackpink','Anderson.Paak','The Free Nationals','Kacey Musgraves','Juice WRLD','Ella Mai','Los Tucanes de Tijuana','FISHER','Jaden Smith','Kraviz','Rosalia','Mon Laferte','Gorgon City','Kruangbin','Kayzo','dvsn','King Princess','Chris Lake','Jauz','Hot Since 82','Charlotte Gainsbourg','SOPHIE','Nicole Moudaber','Tierra Whack','Polo & Pan','Beach Fossils','Yellow Days',' The Frights','Nora En Pure','Yves Tumor','SG Lewis','Kero Kero Bonito','JPEGMAFIA','Calypso Rose','Nic Fanciulli','Kolsch','CamelPhat','Let\'s Eat Grandma','U.S. Girls','Anna Lunoe','Amelie Lens','Hurray for the Riff Raff','Walker & Royce','Turnstile','Rat Boy','88Glam','Ross from Friends','Lauren Lane','Still Woozy','Bakar','Blond:ish','Tomasa del Real','Las Robertas','Dave P.','Tame Impala','Solange','Kid Cudi','Aphex Twin','J Balvin','Weezer','Billie Eilish','Bassnectar','Four Tet','Christine & The Queens','Mac Demarco','Wiz Kalifa','Bazzi','Maggie Rogers','Gryffin','Sheck Wes','Bob Moses','Virgil Ablo','Tale of Us','Mr. Eazi','Sabrina Claudio','Ty Segall & White Fence','Deep Dish','Smino','FKJ','The Interruptors','SiR','Idris Elba','Parcels','JAIN','Soulection','Turnover','SALES','Stephan Bodzin','CloZee','ARIZONA','Murderbeatz','Jambinai','Ame','CHON','Little Simz','Adriatique','Lee Burridge','The Garden','Agoria','Hop Along','shame','Superorganism','Ookay','serpentwithfeet','Steady Holiday','Javiera Mena','The Messthetics','The Red Pears','Heidi Lawden','Ariana Grande','Khalid','Zedd','Gesaffelstein','Bad Bunny','Dillon Francis','CHVRCHES','YG','Cirez D','Playboi Carti','H.E.R.','Blood Orange','Pusha T','Unknown Mortal Orchestra','Kaytranada','Gucci Gang','John Hopkins','SOFFI TUKKER','Burna Boy','Lizzo','Dermot Kennedy','SOBxRBE','Clairo','NGHTMRE','Perfume','boy pablo','Guy Gerber','HYUKOH','Emily King','Dennis Lloyd','Alice Merton','Shallou','070 Shake','Soccer Mommy','Rico Nasty','Cola Boyy','Mansionair','Wallows','Nocturnal Sunshine','Dusky','Yotto','Patrice Baumel','Easy Life','Jon Blomqvist','Iceage','Men I Trust','Charlotte de Witte','Social House','Ocho Ojos','Razorbumps','Tara Brooks']
        # festivals['ROMP']=['Ricky Skaggs & Kentucky Thunder','Trampled by Turtles','The Del McCroury Band','Patty Loveless','Steve Earle & The Dukes','The Wood Brothers','Rhonda Vincent & The Rage','Billy Strings','Jeff Austin Band','Joe Mullins & The Radio Ramblers']
        # festivals['Reggae Rise Up']=['Steel Pulse','Pepper','Common Kings','Sticky Fingers','Josh Heinrichs','Nattali Rize','Bret Bollinger','Oceanstone','Ziggy Marley','Method Man','Redman','J. Boog','Hirie','The Movement','Through The Roots','Arise Roots','Seranation','Summer Survivors','Tribal Seeds','Trevor Hall','Iya Terra','Shwayze','Jah9','Bumpin Uglies','Tribe of I']
        # festivals['High Sierra']=['Greensky Bluegrass','Jim James (Full Band)','St. Paul & The Broken Bones','Galactic','Pigeons Playing Ping Pong','Karl Denson’s Tiny Universe','The Marcus King Band','ALO','The Polish Ambassador','The Nth Power','Jennifer Hartswick Band','Cris Jacobs Band','Cha Wa','Ron Artis II & The Truth']
        # festivals['Backwoods']=['REZZ','Umphrey\'s McGee','Lettuce','Aqueous','Bleep Bloop','Bookie T','Eoto','Eprom','The Infamous Stringdusters','Minnesota','The Motet','Mystic Grizzly','Peekaboo','Pidgeons Playing Ping Pong','PLS&TY','Squnto','Truth','Yheti','Arkansauce','Combsy','Couch Jackets','Dapolitiks','Dalton Richmond','Deep Sequence','Drifters Mile','El Dub','Escape Tones','Flintwick','Fluff','Fractal Sky','Glass Cannon','Groovement','Jonteal','Kadela','Last Sayso','Lethal Cortex','Linear Symmetry','Meesh','M.O.B','Montu','Motto','Mountain Sprout','NGHTWTCHR','NUGSTUFR','Of Faces','Recycled Funk','Refrakt','Ryan Viser','Snowmass']
        # festivals['Hogs for the Cause']=['Trampled by Turtles','Lukas Nelson and the Promise of the Real','The War & Treaty','Dumpstaphunk','George Porter Jr.','Samantha Fish','American Aquarium','Marco Benevento']
        # festivals['Innings']=['Incubus','Sheryl Crow','Cake','Grouplove','Blues Traveler','Roger Clyne & The Peacemakers','Black Pistol Fire','Dorothy','The Baseball Project','Eddie Vedder','Jimmy Eat World','Band of Horses','St.Paul & The Broken Bones','Shakey Graves','Liz Phair','Matt Kearney','G.Love & Special Sauce','The Record Company']
        # festivals['Gasparilla']=['Gary Clark Jr.','Jared & The Mill','Laurie Berkner','Lukas Nelson and the Promise of the Real','Mr. Tommy','New Orleans Suspects\' Tribal Gold','Parrotfish','Sugar Rush','Tank and the Bangas','The Avett Brothers','The Infamous Stringdusters','The Pharcyde','Uncle John\'s Band']
        festivals['Shaky Beats']=['Martin Garrix','Rufus Du Sol','Big Gigantic','FISHER','San Holo','Big Wild','Boogie T','Chris Lake','Ekali','Gryffin','Lane 8','Party Favor','Snakehips','What So Not','Clozee','Cray','Dirty Monkey','Dombresky','Ducky','The Funk Hunters','GG Magree','Midnight Kids','Moon Boots','Paz','Slumberjack','SNBRN','Solardo','Squnto','Vanic','Whipped Cream','Win + Woo','Xie','Zeke Beats','Mantis','Eddie Gold','Movin\' Keyz','DJ Zoe Gray','Airwolf']
        festivals['Bonnaroo']=['Grand Ole Opry','Saba','Space Jesus','Eprom','Shlump','12th Planet','Sunsquabi','All Them Witches','Magic City Hippies','The Nude Party','Rolling Blackouts Coastal Fever','The Comet is Coming','Jack Harlow','Caroline Rose','Donna Missal','Peach Pit','Hekler','Dorfex Box','Phish','Childish Gambino','Solange','The Avett Brothers','Brockhampton','Griz','RL Grime','Beach House','NGHTMRE','Gojira','Courtney Barnett','Girl Talk','AJR','Catfish and the Bottlemen','K.Flay','Anoushka Shankar','Nahko And Medicine For The People','Liquid Stranger','Deafheaven','Parquet Courts','Rival Sons','Ibeyi','Jade Cicada','Las Cafeteras','Cherry Glazerr','The Tesky Brothers','Medasin','Tyla Yaweh','Ducky','Monsieur Perine','Mersiv','Crooked Colours','Post Malone','Odesza','Hozier','Kacey Musgraves','The National','The Lonely Island','ZHU','Juice WRLD','Joe Russo\'s Almost Dead','Gucci Mane','John Prine','Jim James','Maren Morris','Gramatik','Shovels & Rope','Unknown Mortal Orchestra','Quinn XCII','Clairo','Bishop Briggs','Hippo Campus','Tokimonsta','Chelsea Cutler','The Record Company','SNBRN','Ruston Kelly','Whipped Cream','Rubblebucket','Little Simz','Memba','Deva Mahal','DJ Mel','The Lumineers','Cardi B','Brandi Carlile','Illenium','Walk The Moon','Mac Demarco','King Princess','Lil Dicky','G Jones','Trampled By Turtles','The Wood Brothers','Hobo Johnson & The Lovemakers','Princess','The Soul Rebels','The Lemon Twigs','Two Feet','AC Slater','CID','Dombresky','Bombino','Faye Webster','Ripe','Kikagaku Moyo','Iglooghost']
        festivals['BottleRock']=['Neil Young','Imagine Dragons','Mumford & Sons','Logic','Pharell Williams','Santana','One Republic','Sylvan Esso','Flogging Molly','Jenny Lewis','AJR','Anderson East','The Dandy Warhols','lovelytheband','Paul Oakenfold','Alec Benjamin','Neon Trees','Midland','Vintage Trouble','The War And Treaty','Just Loud','Shannon Shaw','Flora Cash','Yoke Lore','Halfnoise','The Dip','Dessa','Liz Cooper & The Stampede','Valley Queen','Jack West','The Forgotten Dreamers','Nathaniel Rateliff & The Night Sweats','Gary Clark Jr.','Juanes','Cypress Hill','Elle King','Marian Hill','Sir Sly','Chevy Metal','Against Me!','Madison Beer','Pink Sweat$','Shannon & The Clams','The Regrettes','White Panda','Elle Duhe','Wilderado','Magic City Hippies','Moonalice','We Banjo 3','Slothrust','Jared & The Mill','Royal Jelly Jive','Rebecca Jade & The Cold Fact','The Blue Stones','Silverado Pickups','Napa Valley Youth Symphony','Tash Sultana','Michael Franti & Spearhead','Lord Huron','Big Boi','Citizen Cope','Bishop Brigs','Gang of Youths','Too $hort','Turkuaz','The Crystal Method','Skylar Grey','Jeff Goldblum & The Mildred Snitzer Orchestra','Houses','The Sould Rebels','Con Brio','Shaed','Welles','The Teskey Brothers','Harry Hudson','Ocean Alley','Sweet Crude','John Craigie','Dustbowl Revival','Jes Frances','The Alive']
        festivals['Governors Ball']=['Tyler, The Creator','Lil Wayne','Brockhampton','Gesaffelstein','Jorja Smith','Blood Orange','Mitski','The Internet','Jessie Reyez','Hippo Campus','MO','Amber Mark','The Voidz','Rolling Blackouts Coastal Fever','Cautious Clay','Jeremy Zucker','Dennis Lloyd','Miles Kane','Hundredth','Still Woozy','Hjomza','Deal Casino','Florence + The Machine','Major Llazer','The 1975','Kacey Musgraves','ZHU','Lord Huron','Vince Staples','Ty Dolla $ign','Playboi Carti','King Princess','Denzel Curry','Clairo','Ravyn Lenae','Saba','Elohim','Sunflower Bean','U.S. Girls','Calpurnia','Dreamers','Suzi Wu','Eazy Life','Tobi Lou','The Strokes','Nas','SZA','Louis The Child','Kaytranada','Sheck Wes','Flatbush Zombies','Joey Bada$$','Lily Allen','Bazzi','Noname','Charli XCX','Bob Moses','SOBxRBE','Chelsea Cutler','070Shake','Parcels','Taylor Bennett','Soccer Mommy','The Underachievers','Kirk Knight','Nick Caution','Jack Harlow','Aaron Aye','Shaed','Ric Wilson','MK Ultra']
        for festival in festivals:
            if not Festival.objects.filter(name__iexact=festival).exists():
                print("adding {}".format(festival))
                festival_entry=Festival(name=festival)
                festival_entry.save()
            festival_row=Festival.objects.get(name__iexact=festival)
            for artist in festivals[festival]:
                if not Band.objects.filter(name__iexact=artist).exists():
                    print("adding both a new band and linking {}".format(festival))
                    band_entry=Band(name=artist)
                    band_entry.save()
                    band_entry.festivals.add(festival_row)
                else:
                    print("linking {}".format(festival))
                    #Band.objects.get(name__iexact=artist).festivals.add(festival_row)
                    bandrows=Band.objects.filter(name__iexact=artist)
                    for row in bandrows:
                        row.festivals.add(festival_row)
    def handle(self, *args, **options):
        self.create_festivals()
