# Generated by Django 2.1.2 on 2018-10-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
