# Generated by Django 2.1.2 on 2018-10-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0003_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_sent',
            field=models.BooleanField(default=False, verbose_name='confirm'),
        ),
    ]
