# Generated by Django 2.1.2 on 2018-10-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0004_profile_confirm_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirm_sent',
        ),
    ]
