# Generated by Django 2.1.2 on 2018-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0005_band_songkickid'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
