# Generated by Django 2.1.2 on 2018-10-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0005_remove_profile_confirm_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_sent',
            field=models.BooleanField(default=False, verbose_name='confirm'),
        ),
    ]
