# Generated by Django 2.1.2 on 2018-10-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0006_profile_confirm_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirm_sent',
        ),
        migrations.AddField(
            model_name='profile',
            name='num_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
