# Generated by Django 2.1.2 on 2018-10-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0007_auto_20181029_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='num_sent',
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
