# Generated by Django 2.1.2 on 2018-11-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalpickr', '0008_auto_20181029_0108'),
        ('festivalpickr', '0008_auto_20181030_1533'),
    ]

    operations = [
    ]
